## 응용 라이브러리

In [19]:
#스레드 제어 준비
import  time as t

#작업 5초
def long_task():
    for w in range(5):
        print(f"일하는 중...{w+1}")
        t.sleep(1)

In [12]:
#일반 제어

#작업 5초 x 5회 = 25초

start = t.time()
print("=====start====")
for n in range(5):
    long_task()
print("======end=====")
print(f"총 작업 시간: {t.time() - start:.2f}초")

=====start====
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
일하는 중...1
일하는 중...2
일하는 중...3
일하는 중...4
일하는 중...5
======end=====
총 작업 시간: 25.03초


In [ ]:
#스레드를 사용함, 프로그램적으로(논리적) 병렬로 처리
import threading
import time as t

start = t.time()
print("=====start====")



# 스레드 제어 준비
threads = []
for n in range(5):
    th = threading.Thread(target=long_task) # 스레드 객체 생성
    threads.append(th) # 스레드 객체를 리스트에 저장
# 스레드 제어   // t로 하면 안됨. 겹치면안되유
for tr in threads:
    tr.start() # 스레드 시작
for tr in threads:
    tr.join() # 스레드가 끝날 때까지 기다림 


print("======end=====")
print(f"총 작업 시간: {t.time() - start:.2f}초")

=====start====
일하는 중...1
일하는 중...1
일하는 중...1
일하는 중...1
일하는 중...1
일하는 중...2일하는 중...2
일하는 중...2

일하는 중...2
일하는 중...2
일하는 중...3
일하는 중...3
일하는 중...3
일하는 중...3
일하는 중...3
일하는 중...4일하는 중...4

일하는 중...4
일하는 중...4
일하는 중...4
일하는 중...5일하는 중...5

일하는 중...5
일하는 중...5
일하는 중...5
======end=====
총 작업 시간: 5.02초


In [ ]:
# multithreading를 사용함, 물리적으로 cpu 코어를 활용하여 병렬처리 / 연산이 많으면 이걸로! // 주피터로 파일만든다음에 폴더에서 터미널로 열엇음

import multiprocessing
import time as t

#작업 5초
def long_task():
    for w in range(5):
        print(f"일하는 중...{w+1}")
        t.sleep(1)

if __name__== "__main__":

    start = t.time()
    print("=====start====")

    processes = []
    for n in range(5):
        p = multiprocessing.Process(target=long_task) # 스레드 객체 생성
        
        processes.append(p) # 스레드 객체를 리스트에 저장
    for p in processes:
        p.start() # 스레드 시작
    for p in processes:
        p.join() # 스레드가 끝날 때까지 기다림 


    print("======end=====")
    print(f"총 작업 시간: {t.time() - start:.2f}초")

=====start====
======end=====
총 작업 시간: 0.07초


## json

In [31]:
test ={
    "name":"superman",
    "age": 20,
    "address":
    {
       "city": "seoul",
       "district"   : "역삼동"
    }
    
    
}
print(test)
print(type(test))

{'name': 'superman', 'age': 20, 'address': {'city': 'seoul', 'district': '역삼동'}}
<class 'dict'>


In [32]:
import json
# json으로 변환

data = json.dumps(test)
print(data)
# json으로 변환된 데이터를 다시 파이썬 객체로 변환
print(type(data))

{"name": "superman", "age": 20, "address": {"city": "seoul", "district": "\uc5ed\uc0bc\ub3d9"}}
<class 'str'>


In [ ]:
# 스마트카 데이터 json 파일 만들기
import json
import time
import random

def generate_smartcar_data(num=0): #{  ,  ,  ,  ,  ,  } 이런식으로 데이터 값이 생성됨
    return {
        "car_id" : num,
        "speed" : random.randint(0, 150), 
        "fuel_level" : random.uniform(0, 100),
        "latitude" : round(random.uniform(-90.0, 90.0),6), # 위도
        "timestamp" : time.time()  # 현재 시간
    }

with open("smartcar_data.json", "w") as file:
    for _ in range(100):  # 100개의 데이터 생성
        data = generate_smartcar_data(n) for n in range(100)
        json.dump(data, file)
        file.write("\n")  # 각 데이터는 한 줄에 저장
    print("스마트카 데이터가 smartcar_data.json 파일에 저장되었습니다.")

SyntaxError: invalid syntax (3454556845.py, line 17)

In [43]:
import os
os.chdir("C:\csh")
os.getcwd()  # 현재 작업 디렉토리 확인

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\user\AppData\Local\Temp\ipykernel_2080\74509877.py:2: SyntaxWarning: invalid escape sequence '\c'
  os.chdir("C:\csh")


'C:\\csh'

In [44]:
for d in data[:5]:
    if d.get("car_id")==3:
        print(d)

KeyError: slice(None, 5, None)

In [59]:
import requests
import json

url = "https://jsonplaceholder.typicode.com/posts"

data = requests.get(url).json()
with open("newdata.json", "w") as f:
    for d in data:
        if d.get("id") >=50 and d.get("id") <=70:  # 예시로 id가 1인 데이터만 출력
            da = d["id"], d["title"]
            json.dump(da, f)
            f.write("\n")  # 각 데이터는 한 줄에 저장


In [79]:
import requests as req
from bs4 import BeautifulSoup as bs

url = "https://finance.naver.com/sise/sise_market_sum.naver"
web = req.get(url)

soup = bs(web.content, "html.parser")
print(soup.title.text)
tableline = soup.select(".type_2 tr")

for t in tableline:
    no = t.select_one(".no")
    title = t.select_one(".tltle")
    number = t.select_one(".number")
    if (no or title or number):
        if(int(str(number.text).replace(",","")) > 80000):
            print(no.text, title.text, int(str(number.text).replace(",","")))

시가총액 : 네이버페이 증권
2 SK하이닉스 280750
3 삼성바이오로직스 1017000
4 LG에너지솔루션 306000
5 KB금융 118300
6 현대차 208000
9 NAVER 253000
10 한화에어로스페이스 847000
11 기아 99400
12 셀트리온 174400
13 HD현대중공업 397500
15 삼성물산 169900
16 현대모비스 308000
17 하나금융지주 94400
19 삼성생명 131600
20 POSCO홀딩스 312500
22 SK스퀘어 181100
25 HD한국조선해양 329000
26 삼성화재 477500
27 현대로템 193600
28 메리츠금융지주 115800
30 LG화학 260750
31 SK이노베이션 116900
32 고려아연 856000
33 크래프톤 356500
34 KT&G 137100
35 SK 224500
36 HD현대일렉트릭 448000
41 삼성SDI 170800
42 LG 82000
43 삼성에스디에스 164300
45 LIG넥스원 568000
48 하이브 277000
49 삼양식품 1476000
50 카카오페이 82400


In [83]:
!pip install -q -U google-genai

In [89]:
from google import genai
def aiai(text):
    client = genai.Client(api_key="AIzaSyBbb1obN-l7SUKsebSPvGEl7KP-bsSolWs")

    response = client.models.generate_content(
        model = "gemini-2.5-flash", contents= text + ";단, 300자 이내로 서술형으로 디테일하게 알려줘. 스마트제조, 스마트팩토리, 스마트팜과 관련된 대답만 해줘"
    )
    print(response.text)

aiai("1word 메모리에 대해 설명해줘")

"1-word 메모리"는 스마트제조, 스마트팩토리, 스마트팜 환경의 센서, 액추에이터 등 **엣지 장치에 내장되는 최소한의 저장 공간**입니다. 이는 **장비 동작/정지, 임계치 도달, 경고 발생 등 단일 이진 상태(0/1)나 극소량 값**을 실시간 저장, 판단에 사용됩니다.

예컨대 스마트팜 관수 펌프 온/오프, 스마트팩토리 제품 통과 여부 등을 즉각 기록하여 **초저전력 엣지 디바이스의 빠른 제어 및 효율적 데이터 처리**를 돕고 시스템 반응성 향상에 기여합니다.


In [93]:
!pip install qrcode

In [94]:
import qrcode

def qrcode_maker(text, filename="qr.png"):
    qr = qrcode.make(text)
    qr.save(filename)

In [95]:
qrcode_maker("ㅎㅇㅎㅇ")

ModuleNotFoundError: No module named 'PIL'

## 넘파이 numpy

In [101]:
# numpy

import numpy as np
data1 = [1, 2, 3, 4, 5]
data2 = [1, 2, 3, 4, 5, 6]

In [98]:
arr3 = np.array([1,2,3],[4,5,6])

NameError: name 'np' is not defined

In [105]:
zz = np.zeros((3,5))  # 10개의 0으로 채워진 배열 생성
zz,zz.shape,zz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [106]:
oo = np.ones((3,5))  # 10개의 1로 채워진 배열 생성
oo,oo.shape,oo.dtype

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 (3, 5),
 dtype('float64'))

In [107]:
np.arange(10)  # 0부터 9까지의 정수로 채워진 배열 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [111]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,20,30],[40,50,60]])
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 20, 30],
        [40, 50, 60]]))

In [112]:
arr1.shape, arr2.shape

((2, 3), (2, 3))

In [117]:
result = arr1 + arr2  # 배열 덧셈
result1 = arr1 - arr2  # 배열 덧셈
result2 = arr1*2-arr2/10
result3 = arr1*arr2


print(result)
print(result1   )
print(result2)
print(result3)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 10  40  90]
 [160 250 360]]


In [120]:
# 1차원과 속성들
#shape : 배열의 차원 정보
#dtype : 배열 원소의 자료형
#size : 배열의 원소 총 개수
arr = np.arange(5)
arr, arr.shape, arr.dtype, arr.size, arr.ndim  # 배열의 차원 수


(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [124]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4],dtype='str')
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [129]:
arr4 = np.full((3,3),"없어요")
arr4
arr5 = np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
arr20 = np.array([1,2],[3,4])
arr20, arr20.shape, arr20.size



TypeError: Field elements must be 2- or 3-tuples, got '3'

In [131]:
arr21 = np.arange(1,5).reshape(2,2)
arr21, arr21.shape, arr21.size

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4)