## 인덱싱(마스크)

In [6]:
# 난수 발생
import numpy as np

ran_data = np.random.randn(8,4)
print(ran_data)


[[ 0.3304336   0.71287614 -0.73852971  0.09682633]
 [ 0.49170062  0.59214703 -1.77884127  1.27614223]
 [-0.4394498  -0.65241013  0.28946141 -0.21974413]
 [ 0.87920915  0.17426131  0.4750377   0.3060984 ]
 [ 0.39724503 -0.11136615  1.5228718   1.49324905]
 [ 0.57729402  0.17064992  0.387517   -1.29558718]
 [ 1.23756904 -0.30987616 -1.1649504   0.58934684]
 [-0.45962843  0.95922562  0.65522763 -1.05228715]]


In [9]:
mask = np.array([True,False,True,False,True,False,True,False])
mask

array([ True, False,  True, False,  True, False,  True, False])

In [10]:
ran_data[mask]

array([[ 0.3304336 ,  0.71287614, -0.73852971,  0.09682633],
       [-0.4394498 , -0.65241013,  0.28946141, -0.21974413],
       [ 0.39724503, -0.11136615,  1.5228718 ,  1.49324905],
       [ 1.23756904, -0.30987616, -1.1649504 ,  0.58934684]])

In [11]:
fruits = np.array(['apple', 'banana', 'kiwi','apple', 'banana', 'kiwi','melon', 'melon'])
fruits

array(['apple', 'banana', 'kiwi', 'apple', 'banana', 'kiwi', 'melon',
       'melon'], dtype='<U6')

In [15]:
fruits_mask = (fruits == 'apple')
fruits_mask

array([ True, False, False,  True, False, False, False, False])

In [16]:
ran_data[fruits_mask]

array([[ 0.3304336 ,  0.71287614, -0.73852971,  0.09682633],
       [ 0.87920915,  0.17426131,  0.4750377 ,  0.3060984 ]])

In [28]:
ran_data[(fruits == 'apple')|(fruits == 'banana'),1:3]

ran_data[:,1:3]


array([[ 0.71287614, -0.73852971],
       [ 0.59214703, -1.77884127],
       [-0.65241013,  0.28946141],
       [ 0.17426131,  0.4750377 ],
       [-0.11136615,  1.5228718 ],
       [ 0.17064992,  0.387517  ],
       [-0.30987616, -1.1649504 ],
       [ 0.95922562,  0.65522763]])

## 인덱스와 마스크

In [29]:
ran_data[ :, 0] >0

array([ True,  True, False,  True,  True,  True,  True, False])

In [32]:
ran_data[ran_data[:,:]>0]

array([0.3304336 , 0.71287614, 0.09682633, 0.49170062, 0.59214703,
       1.27614223, 0.28946141, 0.87920915, 0.17426131, 0.4750377 ,
       0.3060984 , 0.39724503, 1.5228718 , 1.49324905, 0.57729402,
       0.17064992, 0.387517  , 1.23756904, 0.58934684, 0.95922562,
       0.65522763])

In [ ]:
#0710 오전 과제

ran_data[:,0]<0

array([False, False,  True, False, False, False, False,  True])

In [36]:
ran_data[ran_data[:,0]<0,2:4]

array([[ 0.28946141, -0.21974413],
       [ 0.65522763, -1.05228715]])

In [37]:
ran_data

array([[ 0.3304336 ,  0.71287614, -0.73852971,  0.09682633],
       [ 0.49170062,  0.59214703, -1.77884127,  1.27614223],
       [-0.4394498 , -0.65241013,  0.28946141, -0.21974413],
       [ 0.87920915,  0.17426131,  0.4750377 ,  0.3060984 ],
       [ 0.39724503, -0.11136615,  1.5228718 ,  1.49324905],
       [ 0.57729402,  0.17064992,  0.387517  , -1.29558718],
       [ 1.23756904, -0.30987616, -1.1649504 ,  0.58934684],
       [-0.45962843,  0.95922562,  0.65522763, -1.05228715]])